### ISSUE TITLE
Paragraphs or fixed line length

### ISSUE THREAD

**Issue by jayvdb** [imsky/PocketEuler#47]
Starting with Problem 477, some of the lines have been representing complete paragraphs, and are currently at ~250 chars.

Do we want a fixed line length imposed, or do we want paragraphs to be a single line?  There are benefits of both approaches, and the era of tty fixed widths are over, with most terminals being re-sizable and supporting wrapping.

There are a few parsing problems that disappear if there are no line breaks imposed on paragraphs.
The main benefit of a fixed line width is that we choose where the line breaks occur, rather than it occurring automatically.  If we do fixed width, what should it be?

**Comment by imsky** [comment]
single line works for me :ok_hand:

**Comment by jayvdb** [comment]
Just noting that a big benefit of no fixed width is that list items then do not need a blank line between them simply because they are longer than the fixed width.  This is remark warning `list-item-spacing (Missing new line after list item)`, and is described in more detail at http://www.cirosantilli.com/markdown-style-guide/#empty-lines-inside-lists .
