### ISSUE TITLE
Allow squash merging 

### ISSUE THREAD

**Issue by jayvdb** [imsky/PocketEuler#63]
Should we enable squash merging in the settings for this repository?

**Comment by imsky** [comment]
if you think it'd be useful, sure. i don't think there are that many useless commits per PR

**Comment by jayvdb** [comment]
Well #59 is a mess, with commits for unrelated problems.

**Comment by yehoshuapw** [comment]
sorry, bit this is the first time i am using git, for more then only my own use. hopefully fixed up now.

**Comment by imsky** [comment]
let's revisit this if this keeps coming up - generally i favor full history (even if it's messy) but if there are recurring problems, let's consider enabling squash merging
